---
# tasks file for setup-apache-role
- name: Install httpd pkg 
  yum:
   name: httpd
   state: installed
  when: ansible_os_family == "RedHat"
  notify: start httpd service

- name: Install apache2  pkg
  apt:
   name: apache2
   state: installed
  when: ansible_os_family == "Debian"
  notify: start apache2 service

- name: Copying a file
  copy:
   src: index.html
   dest: /var/www/html
   mode: 0666
